In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [3]:
arr3 = np.array([[[1, 2, 3], [1,2 ,3]], [[1, 2, 3], [1,2,3]]])
print(arr3)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [4]:
print(np.__version__)

1.20.3


In [5]:
arr4 = np.array([[[1, 2, 3], [1,2 ,3]], [[1, 2, 3], [1,2,3]]])
print(arr4[1,1,2])

3


In [6]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5[1, -1])

6


In [7]:
arr6 = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(arr6[1:5])
print(arr[-4:-1])

[2 3 4 5]
[2 3 4]


In [8]:
print(arr5[1, 1:3])

[5 6]


In [9]:
print(arr5[0:2, 2])

[3 6]


In [10]:
x = arr6.copy()
y = arr6.view()
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [11]:
print(arr5.shape)

(2, 3)


In [12]:
reshapedArr6 = arr6.reshape(3,3)
print(reshapedArr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
concArr = np.concatenate((arr, arr6))
print(concArr)

[1 2 3 4 5 1 2 3 4 5 6 7 8 9]


In [14]:
concArr2D = np.concatenate((arr4, arr3))
print(concArr2D)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [15]:
splitArr = np.array_split(concArr2D, 4)
print(splitArr)

[array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]]), array([[[1, 2, 3],
        [1, 2, 3]]])]


In [16]:
print(np.sort(arr6))

[1 2 3 4 5 6 7 8 9]
